[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/ffmpeg/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/ffmpeg/ffmpeg-core.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/ffmpeg/ffmpeg-core.worker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/ffmpeg/ffmpeg-core.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/ffmpeg/ffmpeg.min.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cross-Origin-Resource-Policy = "same-origin"
